services:
  welcomebot:
    container_name: welcomebot
    image: git.postfmly.com/admin/welcomebot:arm64
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - LOGO_PORT=8002
      - LOGO_URL=https://welcomebot.postfmly.us/welcomebot.webp
      - LOGO2_URL=https://welcomebot.postfmly.us/welcome.webp
      - TZ=America/Chicago
    env_file: .env
    labels:
      - wud.display.name=WelcomeBot
      - homepage.group=Personal
      - homepage.name=WelcomeBot
      - homepage.icon=https://welcomebot.postfmly.com/welcomebot.webp

networks: {}
